# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Me
    identifier: personal-information
    weight: 10
  - name: Introduction
    parent: personal-information
    url: '#about'
    weight: 11
  - name: Experience
    parent: personal-information
    url: '#experience'
    weight: 12
  - name: Posts
    identifier: post
    weight: 20
  - name: Tech Blogs
    parent: post
    url: 'techblog/'
    weight: 21
  - name: Illustrations
    parent: post
    url: 'illustrations/'
    weight: 22
  - name: Projects
    url: '#projects'
    weight: 30
  #- name: Talks
  #  url: '#talks'
  #  weight: 40
  - name: Featured Contents
    url: '#featured'
    weight: 50
  - name: Publications
    url: '#publications'
    weight: 51
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
